version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: immo
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: pepa-linha
    ports:
      - 8080:8080
